# Generated by Django 3.0.1 on 2020-08-14 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_card_num', models.CharField(blank=True, max_length=25)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('rate_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BarberShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=None)),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('barbers', models.ManyToManyField(related_name='barbers', to='blog.Barber')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='blog.Barber')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=0)),
                ('end_time', models.TimeField(null=True)),
                ('date', models.DateField(default=models.DateField(auto_now=True))),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Barber')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BarberShop')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('sub_time', models.IntegerField(null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BarberShop')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('phone_num', models.CharField(blank=True, max_length=15)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, upload_to=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Person'),
        ),
        migrations.AddField(
            model_name='barber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Person'),
        ),
    ]
